"""Clean-credential launch for the Claude Agent SDK child.

The SDK merges ``os.environ`` under ``ClaudeAgentOptions.env`` when it spawns
the ``claude`` binary, and the bridge inherits the supervisor's full
environment, including the platform-delivered ``ANTHROPIC_API_KEY``. So the
harness never hands the SDK the real binary. It hands it a generated wrapper
that re-executes the binary with the sandbox environment minus the Anthropic
credentials that do not belong to the active auth mode, for every invocation
including the SDK's version probe.

Everything else passes through, exactly as it does for OpenCode: the sandbox
token, ``SESSION_CONFIG`` and user secrets are what ``oi-git-sign``,
``oi-git-credentials``, ``upload-media`` and the agent's own commands need.
The wrapper carries variable *names* only. Credential values travel through
``ClaudeAgentOptions.env`` in process memory and are never written to disk.
"""

from __future__ import annotations

import os
import stat
import sys
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from collections.abc import Mapping

# Credential variables per auth mode. Exactly one mode is ever active: the
# child sees either the key family or the OAuth token, never both, so the
# family of the *other* mode is what the wrapper strips.
API_KEY_CREDENTIAL_VARS: Final[tuple[str, ...]] = (
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_BASE_URL",
    "ANTHROPIC_AUTH_TOKEN",
)
OAUTH_CREDENTIAL_VARS: Final[tuple[str, ...]] = ("CLAUDE_CODE_OAUTH_TOKEN",)

OAUTH_TOKEN_ENV_VAR: Final = "CLAUDE_CODE_OAUTH_TOKEN"
API_KEY_ENV_VAR: Final = "ANTHROPIC_API_KEY"
OAUTH_MANAGED_ENV_VAR: Final = "ANTHROPIC_OAUTH_MANAGED"
CONFIG_DIR_ENV_VAR: Final = "CLAUDE_CONFIG_DIR"

WRAPPER_NAME: Final = "claude-clean-env"


class ClaudeAuthMode(StrEnum):
    API_KEY = "api_key"
    OAUTH_TOKEN = "oauth_token"


@dataclass(frozen=True)
class ClaudeCredential:
    """The one credential the child receives, held in memory only."""

    mode: ClaudeAuthMode
    # Variables to pass through ``ClaudeAgentOptions.env``; never logged.
    env: Mapping[str, str]

    @classmethod
    def api_key(cls, environ: Mapping[str, str]) -> ClaudeCredential | None:
        """Adopt the bridge's Anthropic key family (a user-configured gateway keeps working)."""
        if not environ.get(API_KEY_ENV_VAR):
            return None
        return cls(
            ClaudeAuthMode.API_KEY,
            {name: environ[name] for name in API_KEY_CREDENTIAL_VARS if environ.get(name)},
        )

    @classmethod
    def oauth_token(cls, token: str) -> ClaudeCredential:
        return cls(ClaudeAuthMode.OAUTH_TOKEN, {OAUTH_TOKEN_ENV_VAR: token})


def denylist_for(mode: ClaudeAuthMode) -> tuple[str, ...]:
    """The credential family the child must never see in ``mode``."""
    return OAUTH_CREDENTIAL_VARS if mode is ClaudeAuthMode.API_KEY else API_KEY_CREDENTIAL_VARS


def clean_child_env(
    parent: Mapping[str, str], mode: ClaudeAuthMode, extra: Mapping[str, str]
) -> dict[str, str]:
    """What the child ends up with: parent+extra minus the other mode's credentials.

    This is the reference the sentinel test compares the wrapper's real
    output against.
    """
    merged = {**parent, **extra}
    stripped = set(denylist_for(mode))
    return {name: value for name, value in merged.items() if name not in stripped}


def bundled_claude_binary() -> Path:
    """The ``claude`` binary the pinned SDK wheel ships (``claude_agent_sdk/_bundled``)."""
    import claude_agent_sdk

    package_dir = Path(claude_agent_sdk.__file__).parent
    binary = package_dir / "_bundled" / "claude"
    if not binary.is_file():
        raise FileNotFoundError(f"The Claude Agent SDK wheel has no bundled binary at {binary}")
    return binary


def write_clean_env_wrapper(
    directory: Path,
    *,
    mode: ClaudeAuthMode,
    binary: Path,
    python_executable: str | None = None,
) -> Path:
    """Generate the wrapper set as ``ClaudeAgentOptions.cli_path``.

    A Python script rather than a shell one so the denylist is applied
    exactly (no word splitting, no accidental empty exports). It re-executes
    ``binary`` with its own environment, which is the SDK's merged
    ``os.environ`` + ``options.env``, minus the other mode's credentials.
    """
    python = python_executable or sys.executable
    names = denylist_for(mode)
    script = "\n".join(
        [
            f"#!{python}",
            '"""Generated by the Open Inspect Claude harness. Do not edit."""',
            "import os",
            "import sys",
            "",
            f"BINARY = {str(binary)!r}",
            f"DENYLIST = frozenset({names!r})",
            "",
            "env = {name: value for name, value in os.environ.items() if name not in DENYLIST}",
            "os.execve(BINARY, [BINARY, *sys.argv[1:]], env)",
            "",
        ]
    )
    directory.mkdir(parents=True, exist_ok=True)
    wrapper = directory / WRAPPER_NAME
    wrapper.write_text(script)
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return wrapper


def harness_env(config_dir: Path, credential: ClaudeCredential) -> dict[str, str]:
    """``ClaudeAgentOptions.env``: config dir, policy, and the one credential."""
    return {
        CONFIG_DIR_ENV_VAR: str(config_dir),
        "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1",
        # A background sub-agent returns a result before its work is done and
        # delivers the findings on a later injected turn. Foreground sub-agents
        # launched in one message still run concurrently, as OpenCode's task
        # tool does.
        "CLAUDE_CODE_DISABLE_BACKGROUND_TASKS": "1",
        "DISABLE_AUTOUPDATER": "1",
        "DISABLE_ERROR_REPORTING": "1",
        "DISABLE_TELEMETRY": "1",
        **credential.env,
    }


def resolve_api_key_credential(environ: Mapping[str, str] = os.environ) -> ClaudeCredential | None:
    return ClaudeCredential.api_key(environ)
